// <auto-generated />
using System;
using MeetingRoomsBooking.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetingRoomsBooking.Infrastructure.Persistence.Data.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetingRoomsBooking.Features.Bookings.Domain.Entities.BookingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorRole")
                        .HasColumnType("integer");

                    b.Property<int>("BookingRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("IX_BookingHistories_BookingRequestId");

                    b.HasIndex("BookingRequestId", "CreatedAtUtc")
                        .HasDatabaseName("IX_BookingHistories_BookingRequestId_CreatedAtUtc");

                    b.ToTable("BookingHistories");
                });

            modelBuilder.Entity("MeetingRoomsBooking.Features.Bookings.Domain.Entities.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<string>("MeetingPurpose")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_BookingRequests_IdempotencyKey");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("IX_BookingRequests_Employee_Status");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("IX_BookingRequests_Room_Status_TimeSlot");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("MeetingRoomsBooking.Features.Rooms.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Location")
                        .IsUnique()
                        .HasDatabaseName("UX_Rooms_Name_Location");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MeetingRoomsBooking.Features.Bookings.Domain.Entities.BookingHistory", b =>
                {
                    b.HasOne("MeetingRoomsBooking.Features.Bookings.Domain.Entities.BookingRequest", null)
                        .WithMany("_history")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingRoomsBooking.Features.Bookings.Domain.Entities.BookingRequest", b =>
                {
                    b.OwnsMany("MeetingRoomsBooking.Features.Bookings.Domain.ValueObjects.ParticipantEmail.ParticipantEmail", "_participants", b1 =>
                        {
                            b1.Property<int>("BookingRequestId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("BookingRequestId", "Value");

                            b1.ToTable("BookingParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookingRequestId");
                        });

                    b.OwnsOne("MeetingRoomsBooking.Features.Bookings.Domain.ValueObjects.TimeSlot.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<int>("BookingRequestId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("EndAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartAtUtc");

                            b1.HasKey("BookingRequestId");

                            b1.ToTable("BookingRequests");

                            b1.WithOwner()
                                .HasForeignKey("BookingRequestId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();

                    b.Navigation("_participants");
                });

            modelBuilder.Entity("MeetingRoomsBooking.Features.Bookings.Domain.Entities.BookingRequest", b =>
                {
                    b.Navigation("_history");
                });
#pragma warning restore 612, 618
        }
    }
}
